data:
  sample_rate: 22050
model:
  in_channels: 256
  residual_channels: 16
  skip_channels: 32
  num_blocks: 1
  num_layers: 6
  kernel_size: 2
train:
  batch_size: 4
  learning_rate: 0.001
  total_epochs: 1000
  ckpt_interval: 10
  val_interval: 5
  n_saved: 5
  experiment_name: case0
  resume_from: -1